### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/infografia-CxrlosMX#2]
[Infografia-ciclo de vida del desarrollo web.pdf](https://github.com/SistemasTecTlaxiaco/infografia-CxrlosMX/files/7124609/Infografia-ciclo.de.vida.del.desarrollo.web.pdf)
![CICLO DE VIDA DEL DESARROLLO DE SOFTWARE](https://user-images.githubusercontent.com/77459857/132418112-dd3cf1a1-9994-40ee-be34-7634b5e7f860.png)

**Comment by Rmz-Rigo** [comment]
CALIFICACION:18/20
FALTARON LAS REFERENCIAS

**Comment by josealfredo79** [comment]
Bien hecho y revisado
